name: go-test
version: 1.0.0
icon: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Maven_logo.svg"

inputs:
- name: FLOWCI_GIT_REPO
  type: string
  required: true

- name: WITH_GO_CACHE
  type: string
  required: false
  value: "false"

stats:
- name: "go-coverage"
  desc: "go unit test coverage"
  fields:
    - "coverage"

script: |
  cd ${FLOWCI_GIT_REPO}
  plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/go-test

  GOCMD=go
  GOTEST="$GOCMD test"
  GOGEN="$GOCMD generate"
  GOTOOL="$GOCMD tool"

  if [ $WITH_GO_CACHE == "false" ]; then
    GOTEST="$GOTEST -count=1"
  fi

  $GOGEN ./...
  $GOTEST ./... -v -coverprofile=ci-coverage.out

  $GOTOOL cover -html=ci-coverage.out -o ci-coverage.html
  percent = $($GOTOOL cover -func=ci-coverage.out | grep 'total:' | awk '{print $3}')
  python3 $plugindir/report.py ${percent}

  